apiVersion: v1
kind: Service
metadata:
  name: color-svc # Nombre del Servicio
spec:
  selector:
    app: color # Vincula este servicio con los Pods que tengan la etiqueta app: color
  ports:
  - port: 80 # Puerto expuesto por el servicio internamente
    targetPort: 8080 # Puerto del contenedor al que se envía el tráfico
  type: NodePort # Permite acceso externo desde la IP de los nodos del clúster